aws_region = "eu-west-1"
bucket_name = "virtual-lab-tofu-state"
bucket_policy = "virtual-lab-tofu-state-policy"
iamrole = "vvirtual-lab-tofu-state-s3-iamrole"
dynamodb_table_name = "virtual-lab-tofu-state-dynamo-table"
dynamodb_policy = "virtual-lab-tofu-state-dynamo-table-policy"
key = "opentofu.tfstate"
